name: Publish and Release

on:
  push:
    tags:
      - 'v*' # タグが `v*` の形式（例: v1.0.0）でプッシュされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ResizeCS

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # .NETをセットアップ
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # 使用する.NETのバージョン

      # .NETプロジェクトを復元
      - name: Restore dependencies
        run: dotnet restore

      # .NETプロジェクトをPublish
      - name: Publish  project
        run: |
            dotnet publish -r win-x64 -c Release --self-contained true -o ./${{github.repository}}-win-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true
            dotnet publish -r win-x86 -c Release --self-contained true -o ./${{github.repository}}-win-x86 -p:PublishTrimmed=true -p:PublishSingleFile=true
            dotnet publish -r linux-x64 -c Release --self-contained true -o ./${{github.repository}}-linux-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true
            dotnet publish -r osx-x64 -c Release --self-contained true -o ./${{github.repository}}-osx-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true

      # アーティファクトを圧縮（オプション）
      - name: Zip the published files
        run: | 
            zip -r ./${{github.repository}}-win-x64.zip ./${{github.repository}}-win-x64 
            zip -r ./${{github.repository}}-win-x86.zip ./${{github.repository}}-win-x86 
            zip -r ./${{github.repository}}-linux-x64.zip ./${{github.repository}}-linux-x64 
            zip -r ./${{github.repository}}-osx-x64.zip ./${{github.repository}}-osx-x64 
            

      # リリースを作成してアーティファクトを添付
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }} # タグ名（例: v1.0.0）
          release_name: Release ${{ github.ref_name }}
          assets: ./publish.zip
          body: "Automatically generated release for version ${{ github.ref_name }}."
          draft: true
          artifacts: |
            ./${{github.repository}}-win-x86.zip 
            ./${{github.repository}}-linux-x64.zip
            ./${{github.repository}}-osx-x64.zip