name: Publish and Release

on:
  push:
    tags:
      - 'v*' # タグが `v*` の形式（例: v1.0.0）でプッシュされたときに実行
defaults:
    run:
        working-directory: ./ResizeCS
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # .NETをセットアップ
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # 使用する.NETのバージョン

      # .NETプロジェクトを復元
      - name: Restore dependencies
        run: dotnet restore
          
      # リポジトリ名を環境変数として取得
      - name: Set Repository Name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

        # .NETプロジェクトをPublish
      - name: Publish  project
        run: |
            dotnet publish -r win-x64 -c Release --self-contained true -o ./${{ env.REPO_NAME }}-win-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true 
            dotnet publish -r win-x86 -c Release --self-contained true -o ./${{ env.REPO_NAME }}-win-x86 -p:PublishTrimmed=true -p:PublishSingleFile=true 
            dotnet publish -r linux-x64 -c Release --self-contained true -o ./${{ env.REPO_NAME }}-linux-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true 
            dotnet publish -r osx-x64 -c Release --self-contained true -o ./${{ env.REPO_NAME }}-osx-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true 

      # アーティファクトを圧縮（オプション）
      - name: Zip the published files
        run: | 
            zip -r ./${{ env.REPO_NAME }}-win-x64.zip ./${{ env.REPO_NAME }}-win-x64 
            zip -r ./${{ env.REPO_NAME }}-win-x86.zip ./${{ env.REPO_NAME }}-win-x86 
            zip -r ./${{ env.REPO_NAME }}-linux-x64.zip ./${{ env.REPO_NAME }}-linux-x64 
            zip -r ./${{ env.REPO_NAME }}-osx-x64.zip ./${{ env.REPO_NAME }}-osx-x64 

      - name: ls
        run: |
            ls
            pwd
            
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: release-artifacts-${{ env.REPO_NAME }}-${{ github.ref_name }}
            path: |
                ${{ env.REPO_NAME }}-win-x64.zip
                ${{ env.REPO_NAME }}-win-x86.zip
                ${{ env.REPO_NAME }}-linux-x64.zip
                ${{ env.REPO_NAME }}-osx-x64.zip

      # リリースを作成してアーティファクトを添付
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }} # タグ名（例: v1.0.0）
          name: Release ${{ github.ref_name }}
          body: "Automatically generated release for version ${{ github.ref_name }}."
          draft: true
          artifacts: |
                ${{ env.REPO_NAME }}-win-x64.zip
                ${{ env.REPO_NAME }}-win-x86.zip
                ${{ env.REPO_NAME }}-linux-x64.zip
                ${{ env.REPO_NAME }}-osx-x64.zip